library(tidyverse)
library(httr)

## Purpose: Use 2017 rent stabilized property list generated by taxbills.nyc to determine rent stabilized ratio for properties in Brooklyn

## Read in taxbills file
taxbills2017_raw <- read_csv("raw/rs2017.csv")
taxbills2017_raw_bk <- taxbills_raw |> 
  filter(borough == "BK") |> 
  select(ucbbl, `2017uc`, `2017est`) |> 
  rename(BBL = `ucbbl`)

## Load in 2017 PLUTO BBLs and unit counts
pluto2017_bk <- st_read("raw/BKMapPLUTO.shp") |> 
  st_drop_geometry() |> 
  select(BBL, UnitsRes)

## Join taxbills data to all BK properties and calculate share of rent stabilized units
rentstab2017_joined <- pluto2017_bk |> 
  left_join(taxbills_raw_bk, by = "BBL") |> 
  mutate(shareRS = if_else(!is.na(`2017uc`), (`2017uc`/UnitsRes), 0))

## 723 BBLs generated rent stabilized shares greater than 1. Remove these BBLs from the final dataframe
rentstab2017_summary <- rentstabTB_joined |> 
  mutate(shareRS = if_else(shareRS > 1, 0, shareRS)) |> 
  rename(bbl = "BBL") |> 
  select(bbl, shareRS)
