library(tidyverse)
library(sf)
library(httr)

## Purpose: Use 2021 rent stabilized property list generated by taxbills.nyc and JustFix to determine rent stabilized ratio for properties in Brooklyn

## Read in taxbills file
taxbills2021_raw <- read_csv("https://s3.amazonaws.com/justfix-data/rentstab_counts_from_doffer_2021.csv") |> 
  select(bbl = ucbbl, uc2021)

## Join taxbills data to all 2023 BK lots and calculate share of rent stabilized units
rentstab21_joined <- plutolots_2023 |> 
  select(bbl, unitsRes) |> 
  left_join(taxbills2021_raw, by = "bbl") |> 
  select(bbl, uc2021, unitsRes) |> 
  mutate(shareRS = if_else(!is.na(uc2021), (uc2021/unitsRes), 0))

## 723 BBLs generated rent stabilized shares greater than 1. Remove these BBLs from the final dataframe
rentstab21_summary <- rentstab21_joined |> 
  st_drop_geometry() |> 
  mutate(shareRS = if_else(shareRS > 1, 0, shareRS)) |> 
  select(bbl, shareRS)
